// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZK4tQPGBXtsU7FPbmayUraNf-2v8XC10',
    appId: '1:886123658854:web:b2bc8083b953a74f91b7a7',
    messagingSenderId: '886123658854',
    projectId: 'crud-memo',
    authDomain: 'crud-memo.firebaseapp.com',
    storageBucket: 'crud-memo.appspot.com',
    measurementId: 'G-5MHXDW599P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoo0xek77LDfJifYyyad7hsNxHoc7HCNw',
    appId: '1:886123658854:android:a6aa8a41db94c55491b7a7',
    messagingSenderId: '886123658854',
    projectId: 'crud-memo',
    storageBucket: 'crud-memo.appspot.com',
  );
}
